import { StoreObject } from "lib/redux";

const store: StoreObject = {
    key: "hud",
    initialState: {
        altitude: 0,
        altitudeShow: false,
        autopilotShow: false,
        armor: 100,
        beltShow: false,
        buffedAgility: false,
        buffedAlertness: false,
        buffedArmor: false,
        buffedDouble: false,
        buffedHealth: false,
        buffedHunger: false,
        buffedInt: false,
        buffedJobpay: false,
        buffedThirst: false,
        buffedOxygen: false,
        buffedStamina: false,
        buffedStress: false,
        buffedStrength: false,
        buffedBikeStats: false,
        burgerShotIntercom: false,
        crosshairShow: false,
        display: false,
        displayAllForce: false,
        displayAllForceVehicle: false,
        displayRadioChannel: false,
        displayBlackjackTimer: false,
        displayRouletteTimer: false,
        displayFoodWater: false,
        engineDamageShow: false,
        partsDamageShow: false,
        food: 100,
        fuel: 0,
        gasDamageShow: false,
        harnessDurability: 0,
        hasParachute: false,
        health: 100,
        mana: 0,
        manaShow: false,
        nos: 0,
        nosEnabled: false,
        nosShow: false,
        hardcoreScore: 0,
        pursuit: 0,
        pursuitShow: false,
        collarShow: false,
        boostCompletions: 0,
        weaponFireRate: 0,
        showWeaponFireRate: false,
        showDriftMode: false,
        driftMode: false,
        showDriftThread: false,
        driftThread: 100,
        displayBoostingMinigameCooldown: false,
        oxygen: 100,
        oxygenShow: false,
        stamina: 100,
        staminaShow: false,
        radarShow: false,
        showMethLabStatus: false,
        methLabStatus: {
            FRIDGE_TEMPERATURE: 100,
            MIXER_HARDWARE: 100,
            MIXER_INGREDIENTS: 100,
            MIXER_TEMPERATURE: 100,
            DISTIL_STEAM: 100,
            DISTIL_SETTINGS: 100,
        },
        stress: 0,
        voiceActive: false,
        voiceActiveRadio: false,
        voiceRange: 2,
        voipStatus: true,
        water: 100,
        waypointActive: false,
        waypointDistance: 1.2,
        godModeEnabled: false,
    }
};

export default store;