fx_version 'cerulean'
game 'gta5'

this_is_a_map 'yes'

data_file 'DLC_ITYP_REQUEST' 'stream/legacy_to_be_removed/discoverybuilder.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/building/np_housing_building.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/doors/np_housing_doors.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/stairs/np_housing_stairs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/lights/np_housing_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/water/np_housing_water.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/text/np_housing_text.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/duct/np_housing_duct.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/frames/np_housing_frames.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/decals/np_housing_decals.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/shadows/np_housing_shadows.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/electrical/np_housing_electrical.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/premade_kits/np_housing_premade_kits.ytyp'
dependency '/assetpacks'